const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#E31C25",
    background: "#F5F5F5",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#E31C25",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#1a1a1a",
    muted: "#F0F0F0",
    mutedForeground: "#888888",
    accent: "#FF3B30",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#E5E5E5",
    input: "#E5E5E5",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#E31C25",
    background: "#0D0D0D",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#E31C25",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A2A",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#FF3B30",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
    success: "#30D158",
    warning: "#FFD60A",
  },
  radius: 12,
};

export default colors;
