export const DUMMY_USER = {
  id: "u1",
  name: "Alex Johnson",
  email: "alex@example.com",
  phone: "+1 (555) 123-4567",
  membershipType: "Premium",
  membershipExpiry: "2026-12-31",
  joinDate: "2024-01-15",
};

export const DUMMY_MEMBERSHIP = {
  id: "m1",
  type: "Premium",
  startDate: "2026-01-01",
  endDate: "2026-12-31",
  status: "active",
  features: [
    "Unlimited gym access",
    "2 personal training sessions/month",
    "Group classes included",
    "Sauna & steam room",
    "Nutrition consultation",
    "App tracking",
  ],
  price: 99.99,
  nextBillingDate: "2026-05-01",
  autoRenew: true,
};

export const DUMMY_ATTENDANCE = [
  { id: "a1", date: "2026-04-13", checkIn: "07:30", checkOut: "09:00", duration: 90 },
  { id: "a2", date: "2026-04-11", checkIn: "06:45", checkOut: "08:15", duration: 90 },
  { id: "a3", date: "2026-04-09", checkIn: "18:00", checkOut: "19:30", duration: 90 },
  { id: "a4", date: "2026-04-07", checkIn: "07:00", checkOut: "08:30", duration: 90 },
  { id: "a5", date: "2026-04-05", checkIn: "09:00", checkOut: "10:30", duration: 90 },
  { id: "a6", date: "2026-04-03", checkIn: "17:30", checkOut: "19:00", duration: 90 },
  { id: "a7", date: "2026-04-01", checkIn: "06:00", checkOut: "07:30", duration: 90 },
];

export const DUMMY_WORKOUT_PLANS = [
  {
    id: "w1",
    name: "Strength Builder",
    level: "Intermediate",
    duration: "8 weeks",
    daysPerWeek: 4,
    goal: "Build muscle mass",
    trainer: "Marcus Reid",
    exercises: [
      { name: "Bench Press", sets: 4, reps: "8-10", rest: "90s" },
      { name: "Squats", sets: 4, reps: "8-10", rest: "90s" },
      { name: "Deadlifts", sets: 3, reps: "6-8", rest: "120s" },
      { name: "Overhead Press", sets: 3, reps: "8-10", rest: "90s" },
      { name: "Barbell Rows", sets: 4, reps: "8-10", rest: "90s" },
      { name: "Pull-ups", sets: 3, reps: "To failure", rest: "60s" },
    ],
    isActive: true,
  },
  {
    id: "w2",
    name: "Fat Burn HIIT",
    level: "Advanced",
    duration: "4 weeks",
    daysPerWeek: 5,
    goal: "Lose fat, increase endurance",
    trainer: "Sarah Chen",
    exercises: [
      { name: "Box Jumps", sets: 4, reps: "15", rest: "30s" },
      { name: "Burpees", sets: 4, reps: "20", rest: "30s" },
      { name: "Mountain Climbers", sets: 4, reps: "30s", rest: "15s" },
      { name: "Kettlebell Swings", sets: 3, reps: "20", rest: "45s" },
    ],
    isActive: false,
  },
];

export const DUMMY_DIET_PLANS = [
  {
    id: "d1",
    name: "High Protein Bulk",
    calories: 3200,
    protein: 180,
    carbs: 350,
    fat: 90,
    goal: "Muscle gain",
    dietitian: "Dr. Emily Foster",
    meals: [
      {
        type: "Breakfast",
        items: ["6 egg whites + 2 whole eggs", "1 cup oatmeal with berries", "Protein shake"],
        calories: 650,
        time: "7:00 AM",
      },
      {
        type: "Lunch",
        items: ["200g chicken breast", "1 cup brown rice", "Mixed vegetables", "Olive oil"],
        calories: 700,
        time: "12:30 PM",
      },
      {
        type: "Pre-workout",
        items: ["Banana", "30g whey protein"],
        calories: 250,
        time: "4:00 PM",
      },
      {
        type: "Dinner",
        items: ["200g salmon", "Sweet potato", "Broccoli", "Salad"],
        calories: 750,
        time: "7:30 PM",
      },
    ],
    isActive: true,
  },
];

export const DUMMY_CLASSES = [
  {
    id: "c1",
    name: "Power Yoga",
    instructor: "Lisa Park",
    time: "7:00 AM",
    date: "2026-04-14",
    duration: 60,
    capacity: 20,
    enrolled: 15,
    location: "Studio A",
    level: "All levels",
    isBooked: false,
    category: "Yoga",
  },
  {
    id: "c2",
    name: "CrossFit WOD",
    instructor: "Marcus Reid",
    time: "6:00 AM",
    date: "2026-04-14",
    duration: 45,
    capacity: 15,
    enrolled: 14,
    location: "Main Floor",
    level: "Advanced",
    isBooked: true,
    category: "HIIT",
  },
  {
    id: "c3",
    name: "Spin Cycle",
    instructor: "Tom Hughes",
    time: "9:00 AM",
    date: "2026-04-14",
    duration: 45,
    capacity: 25,
    enrolled: 10,
    location: "Cycle Room",
    level: "Intermediate",
    isBooked: false,
    category: "Cardio",
  },
  {
    id: "c4",
    name: "Body Pump",
    instructor: "Sarah Chen",
    time: "11:00 AM",
    date: "2026-04-15",
    duration: 60,
    capacity: 30,
    enrolled: 22,
    location: "Studio B",
    level: "Beginner",
    isBooked: false,
    category: "Strength",
  },
  {
    id: "c5",
    name: "Boxing Cardio",
    instructor: "Jake Rivera",
    time: "5:30 PM",
    date: "2026-04-15",
    duration: 60,
    capacity: 18,
    enrolled: 18,
    location: "Boxing Ring",
    level: "Intermediate",
    isBooked: false,
    category: "HIIT",
  },
];

export const DUMMY_NOTIFICATIONS = [
  {
    id: "n1",
    type: "class",
    title: "Class Reminder",
    message: "CrossFit WOD starts in 1 hour. Don't forget your gym bag!",
    time: "5:00 AM",
    date: "2026-04-14",
    read: false,
  },
  {
    id: "n2",
    type: "payment",
    title: "Payment Due",
    message: "Your membership renewal is due in 7 days. Auto-renew is enabled.",
    time: "9:00 AM",
    date: "2026-04-10",
    read: false,
  },
  {
    id: "n3",
    type: "achievement",
    title: "Achievement Unlocked!",
    message: "You completed 20 workouts this month! You're on fire!",
    time: "6:00 PM",
    date: "2026-04-08",
    read: true,
  },
  {
    id: "n4",
    type: "trainer",
    title: "Message from Marcus",
    message: "Great session today! I've updated your workout plan for next week.",
    time: "10:30 AM",
    date: "2026-04-07",
    read: true,
  },
  {
    id: "n5",
    type: "promotion",
    title: "Weekend Special",
    message: "Bring a friend this weekend for FREE! Limited offer.",
    time: "8:00 AM",
    date: "2026-04-05",
    read: true,
  },
];

export const DUMMY_PROGRESS = [
  { id: "p1", date: "2026-04-01", weight: 82.5, bodyFat: 18.2, muscleMass: 38.5, bmi: 24.1 },
  { id: "p2", date: "2026-03-01", weight: 83.8, bodyFat: 19.0, muscleMass: 38.0, bmi: 24.5 },
  { id: "p3", date: "2026-02-01", weight: 85.0, bodyFat: 19.8, muscleMass: 37.5, bmi: 24.9 },
  { id: "p4", date: "2026-01-01", weight: 86.2, bodyFat: 20.5, muscleMass: 37.0, bmi: 25.2 },
  { id: "p5", date: "2025-12-01", weight: 87.5, bodyFat: 21.0, muscleMass: 36.5, bmi: 25.6 },
];

export const DUMMY_PAYMENTS = [
  {
    id: "pay1",
    type: "Membership",
    description: "Premium Membership - April 2026",
    amount: 99.99,
    date: "2026-04-01",
    status: "paid",
    method: "Visa •••• 4242",
  },
  {
    id: "pay2",
    type: "Membership",
    description: "Premium Membership - March 2026",
    amount: 99.99,
    date: "2026-03-01",
    status: "paid",
    method: "Visa •••• 4242",
  },
  {
    id: "pay3",
    type: "Personal Training",
    description: "Personal Training Session x4",
    amount: 200.00,
    date: "2026-02-15",
    status: "paid",
    method: "Mastercard •••• 8821",
  },
  {
    id: "pay4",
    type: "Membership",
    description: "Premium Membership - February 2026",
    amount: 99.99,
    date: "2026-02-01",
    status: "paid",
    method: "Visa •••• 4242",
  },
];

export const DUMMY_TRAINER = {
  id: "t1",
  name: "Marcus Reid",
  specialty: "Strength & Conditioning",
  avatar: null,
  messages: [
    { id: "m1", from: "trainer", text: "Hey! How was the workout yesterday?", time: "10:00 AM", date: "2026-04-12" },
    { id: "m2", from: "user", text: "It was intense but great! My legs are sore.", time: "10:15 AM", date: "2026-04-12" },
    { id: "m3", from: "trainer", text: "That's the sign of a good workout. Rest tomorrow and hydrate well.", time: "10:18 AM", date: "2026-04-12" },
    { id: "m4", from: "trainer", text: "I've updated your plan for next week. Check it out!", time: "10:30 AM", date: "2026-04-13" },
  ],
};
